# Documentation Usage

Everything you have visibility to within the Metabase environment is documented. Meaning, every table you see has a description which includes the URL of where the data is collected (as well as the web scraping methodology where informative), and every field within those tables has also been documented on [predictcryptodb.com](https://predictcryptodb.com). Every table you have visibility to also has an e-mail alert system that alerts me if the data stops flowing through on an hourly (or daily for some) basis. If anything becomes broken I will remove the visibility of that table within Metabase, so if a table is found within the Metabase environment you can assume the web scraper for that table is still functioning correctly and that the data is uploaded to the table on an automated schedule. I think Metabase could do a better job at making the documentation for the different tables more intutitive to find, so hopefully this guide can provide some clarity where Metabase might be lacking.

## pkDummy and pkey


## Navigating the Metabase interface



## Using x-rays to explore a table

- caveat that the database doesn't have the greatest resources that a big company would be able to provide and how this database costs around $220 a month to maintain vs. what a company would spend


(could really use a section on explaining the way pkDummy, pkey work and how they follow two different time zones, show Alteryx trick to deal with the trickiness of UTC not having daylight savings and our local times having it)
